// Generated by https://quicktype.io

export interface TDoctors {
  status: string;
  results: number;
  doctors: TDoctor[];
}

export interface TDoctor {
  id: number;
  user: TUser;
  medicalAppointmentDates: TMedicalAppointmentDate[];
  specialty: string;
}

export interface TMedicalAppointmentDate {
  id: number;
  date: string;
  status: TStatus;
}

export enum TStatus {
  Pending = "pending",
  Selected = "selected",
}

export interface TUser {
  firstName: string;
  lastName: string;
  email: string;
  telephone: string;
  status: string;
}
